### ISSUE TITLE
Verify currency handling

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/example-storefront#117]
## Issue

With the catalogItemProduct query, you can get the currency for the product by adding a subfield for `shop.currency.code`. 

```graphql
product {
      shop {
        currency {
          code
        }
      }
}
```

You can also get the currency for the primary shop by using the `@withShop` decorator.
In a single shop situation, both will produce the same currency code. 

This breaks down when

1. Users can switch currency
2. Multiple shops with different currencies. ( `@withShop` only provides the primary shop )

## Questions

- Where should the currency code come from. The shop, the user, or the product?

- Should I be able to do get the currency of the product by user? Or expect to get it from the viewer?

```graphql
product {
      user {
        currency {
          code
        }
      }
}
```

**Comment by spencern** [comment]
We discussed this ticket today, here's a few notes that are relevant:
1. There is more thinking that needs to be done on the issues of currency and pricing, we're not ready to make decisions quite yet.
2. Whether a product shop is part of a "Marketplace" vs a "Multi-tenant" setup may impact the precedence that determines which currency to use 
3. We should consider adding a pricing resolver that deals with currency and pricing logic and only publish a single price to the client.

**Comment by aldeed** [comment]
While there are still good questions we need to answer on the server side, the answer should be pretty simple for the client app.
- It should never need to know what the currency is
- It should use `displayAmount` when displaying, which already has the currency symbol
- It should use `amount` for any necessary mutation values and calculations, although ideally all calculations should also be done on the server.

I'm updating this issue to be a review of currency handling throughout the app to make sure that the above is true. Fixes or additional api-side issues might be created based on this review.

**Comment by spencern** [comment]
@mikemurray we crossed this off the list during our last retro - can we close this issue now or is there more to do?

**Comment by aldeed** [comment]
@spencern I just did a quick review and I see a bunch of places where it isn't being done as I would expect. I'd leave this open for now, but I'll try to write more specific issues.
