### ISSUE TITLE
Revisit caching withCart decorator mutation results

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/example-storefront#193]
# Issue

Revisit caching the result of the `createCart` and `addCartItems` in the `@withCart` decorator. Apollo should be updating the cache after these mutations, but it currently isn't.

# Solution

- Research methods to update the cache with Apollo mutations
- Implement solution and test

**Comment by spencern** [comment]
@mikemurray will you check to see if this should be a release blocker?

**Comment by mikemurray** [comment]
@spencern This shouldn't be a release blocker as things are working now. If there is time before the release then an attempt may be made to make the necessary updates; otherwise, this can wait until after the release.

**Comment by willopez** [comment]
@mikemurray updating the local cache as seen in the following link, works for me: https://github.com/reactioncommerce/reaction-next-starterkit/blob/develop/src/containers/cart/withCart.js#L78

**Comment by spencern** [comment]
@mikemurray @willopez can we close this issue?
