### ISSUE TITLE
Add confirmation modal for removing items from cart during checkout

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/example-storefront#241]
# Issue

A user can remove items from their cart during checkout (up to the final "Review and place order" step), either by editing the quantity or clicking Remove. This creates a bad experience, since items that may have been removed in error (ie, by toggling the quantity to 0 or clicking remove by accident) can't be recovered easily. The user will be removed from Checkout entirely when the last item is removed from the cart, and see the Empty Cart message. 

# Solution

Specifically in Checkout, add a confirmation modal when an item is removed from the cart. 
Clicking _Cancel_ will keep the item in the cart. 
Clicking _Remove_ will remove the item. If it's the last item in the cart, the user should see the Empty Cart message. 
Clicking outside of the modal will cancel the action and keep the item in the cart. 

Mock: http://zpl.io/VDnnrol

<img width="1078" alt="screen shot 2018-08-21 at 12 24 27 pm" src="https://user-images.githubusercontent.com/36006187/44421227-2b217080-a53d-11e8-9f48-60ad30772e71.png">

**Comment by cassytaylor** [comment]
Not sure if this should be labeled 'bug' or 'enhancement'...

**Comment by cassytaylor** [comment]
@aldeed this might not be needed anymore, per a conversation with @spencern and @mikemurray today wherein we decided it would make the most sense to remove the quantity toggle/remove button entirely from checkout

**Comment by cassytaylor** [comment]
.. which would solve this problem and lots of others

**Comment by aldeed** [comment]
@cassytaylor Wouldn't it be best to confirm everywhere, not just during checkout? Alternatively we could do something like a "Removed" overlay on the item with an "Undo" button, which shows for a couple seconds. That's a bit more work, though.

**Comment by cassytaylor** [comment]
@aldeed if we were to confirm everywhere, I do like the overlay idea, since it's less intrusive than a modal (and is a more elegant solution in general)
