### ISSUE TITLE
PDP: Add photos for the color options

### ISSUE THREAD

**Issue by rosshadden** [reactioncommerce/example-storefront#285]
Split off from #258.

This would require both data and assets. We need to know the colors available for each product, and have images per color per product. And of course the item schema needs to support this data, and the API calls need to support storing and sending it.

## Designs

<img width="662" alt="screen shot 2018-11-20 at 11 17 34 am" src="https://user-images.githubusercontent.com/3673236/48797003-f052e400-ecb5-11e8-8925-0f42c6427d18.png">
<img width="411" alt="screen shot 2018-11-20 at 11 17 42 am" src="https://user-images.githubusercontent.com/3673236/48797004-f052e400-ecb5-11e8-888d-2e65e38e7aa2.png">

**Comment by aldeed** [comment]
Yep, this is dependent on the bigger attributes and Product model refactors that we'll be doing soon.
