### ISSUE TITLE
Create placeholder home page and point index route to it

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/example-storefront#298]
Currently the default route is pointed at a Product Grid page which is unlikely to be useful to anyone building real sites. It would be better to point to a placeholder `home` file and move the current home page into a `productGrid` file. This would make it easier to customize in most common use cases I believe. This might want to default to pointing to a `<Homepage>` component in the `custom` directory.

**Comment by aldeed** [comment]
@cassytaylor @rymorgan Any thoughts here? Do you have any designs for what a placeholder / demo home page would look like?

**Comment by rymorgan** [comment]
I wholeheartedly agree with @zenweasel about this. Eventually, this will be connected to some kind of CMS operator experience as well. 

Yes, we have designs for this - 
web link - https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5afc85bfb7edeb431d67aa81
app link - zpl://project?pid=5afc82f5e8d73e250ff9d855&seid=5afc85bfb7edeb431d67aa81
