### ISSUE TITLE
Design Review Epic: TopNav behavior for desktop and touch/mobile 

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/example-storefront#319]
The behaviors for opening/closing the top nav menu are:

- On any touch interface, the nav should open on tap.
- On any horizontal tablet, 960 width and down, the nav should open on hamburger press.
- On any vertical tablet, the nav should open on tap.
- On desktop, the nav should open on hover.

Breakpoints and specs for the top nav menu: http://zpl.io/VDz7kQJ (at the bottom)

**Comment by zenweasel** [comment]
@kieckhafer Erik will be working on a rewrite of the nav here to accommodate the new work we are doing around Navigation for CMS integration. This can probably be looked at then.

**Comment by cassytaylor** [comment]
@kieckhafer hmmm, I think these are just weirdly written specs. not sure what was meant by that!
