### ISSUE TITLE
Bug: Add to cart button should have a lightened hover color

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/example-storefront#329]
Similar color styles as this Important button https://stoic-hodgkin-c0179e.netlify.com/#!/Button

**Comment by aldeed** [comment]
We should just change it to BE the comp lib Button with `actionType="important"`

**Comment by HarisSpahijaPon** [comment]
As a matter of fact I noticed that this bug happens with a lot of hovers. Also the hover on deleteinputbutton on checkoutform seems to not show correct styling. Are there any more buttons that do not show correct hovers that you guys are aware of?

**Comment by aldeed** [comment]
None I'm aware of, but haven't done a thorough check
