### ISSUE TITLE
Support for custom routes and pages

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/example-storefront#403]
### Feature Name
Support for custom routes and pages

### Summary description
We need to be able to add a custom route without needing to write directly into the routes file. Additionally, it will be beneficial to be able to add a page not in the pages directory.

### Rationale for why this feature is necessary
This will reduce possible conflicts with upstream changes

### Expected use cases
A custom route is needed as Paypal return URL

**Comment by mikemurray** [comment]
Pages in next are custom routes. The routes in `routes.js` file will let you make aliases for page routes. 

If you wanted to handle some PayPal based functionality, then you can always do so with a page component. 

In `getInitialProps` you have access to the same `req` and `res` objects from express and can do with them what you want.

**pages/paypal.js**

```js
import React, { Component } from "react";

class PayPal extends Component {
  static async getInitialProps(ctx) {
    console.log("req", ctx.req);
    console.log("res", ctx.res);
  }

  render() {
    return <div>Nothing here, or just return null</div>;
  }
}

export default PayPal;
```

---

Not adding a page to the `pages` directory seems like fighting against the premise of `next.js`, and the starterkit being a forkable "starter kit".

---

With that, I pose the following questions the following questions...

- How much customization do we allow for the starter kit through pluggable interfaces?
- At what point is it up the end developer to build the solution they want to see?
- What is the cut-off for upstream support?

These are questions I think we've sorta answered, but I think we to continually clarify the intended purpose of the sharterkit.
