### ISSUE TITLE
PDP doesn't select the variant based on the URL

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/example-storefront#408]
Type: **major**

**Describe the bug**

PDP page does not respect the selected variant from the URL for both the SSR rendered app nor the browser.

- SSR page has no variant selected.
- Browser app always selects the first variant/option

For example, the price doesn't show up, because a variant needs to , and any selected variants aren't selected.

**To Reproduce**

1. Go to a PDP page
2. See that the price / compare at price , and options (if available) are not visible or selected for a split second
3. After a second, things pop after the browser app executes the selection of the initial variant

---

1. Go to The URL `http://localhost:4050/product/light-up-high-tops/cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3RWYXJpYW50OkRYQmtKTkdlV01IMlFxZVRl`
1. See that `Black / 7` is selected, **however...** `That URL is for `Red / 8`

**Expected behavior**

- Left: SSR page has no variant selected so it's missing the price and focus ring around the top variant
- Right: Im the browser the first variant is selected

PDP page should select the variant provided by the URL for both the SSR page and browser app.

**Screenshots**

![argentinian_bullhide_campero_hat___reaction_and_argentinian_bullhide_campero_hat___reaction_and_new_issue_ _reactioncommerce_reaction-next-starterkit](https://user-images.githubusercontent.com/42217/47582394-141a4880-d909-11e8-8a1d-e9936c63f82a.png)

**Desktop (please complete the following information):**
- OS: MacOS Mojave
- Browser Chrome
- Version 69.0.3497.100

**Comment by mikemurray** [comment]
Fixed in https://github.com/reactioncommerce/reaction-next-starterkit/issues/321

**Comment by zenweasel** [comment]
I don't see a PR that closes this issue. #321 is just a duplicate issue
