### ISSUE TITLE
CheckoutActions & CheckoutPage need a good refactor.

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/example-storefront#439]
Type: **critical**

**Describe the bug**
The starter kit checkout was built in parallel with the GQL API & component-library checkout components. A lot of the starter kit checkout code was written while the other two projects were in flux and it has become one of the more confusing parts of this project. Now that the API and component-lib are more stable we need to refactor the checkout to be more in line with other established patterns.

**Expected behavior**
I would like to see a refactor that eliminates the starterkit's `components/CheckoutActions` component completely and have the CheckoutPage or HOCs responsible for the checkout

**Comment by HarisSpahijaPon** [comment]
I would like to pick this one up. Trying to implement custom checkoutactions have been nothing but frustrating and near impossible to me so far without running into a ton of sideffects. Do you have any idea on how to approach this @nnnnat ? 

If you could give me some guidelines I could refactor everything.
