### ISSUE TITLE
Can't access port 4000 [Connection refused]

### ISSUE THREAD

**Issue by rlamostre0** [reactioncommerce/example-storefront#493]
Type: **critical**

**Bug**
Can't access page

*Commit hash*	
23c127a412e391af29fb8ebb7765009489b2a1d7

**To Reproduce**
~/reaction-platform$ make start
Starting reaction-hydra_postgres_1 ... done
Starting reaction-hydra_hydra-migrate_1 ... done
Starting reaction-hydra_hydra_1         ... done
Starting reaction_mongo_1 ... done
Starting reaction_reaction_1 ... done
Starting reaction-next-starterkit_web_1 ... done

~/reaction-platform$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS              PORTS                                                      NAMES
3e52c582a7dc        reaction-next-starterkit_web      "/usr/local/src/reac…"   About a minute ago   Up 9 seconds        0.0.0.0:4000->4000/tcp                                     reaction-next-starterkit_web_1
b3a28eee22f1        reaction_reaction                 "bash -c 'meteor npm…"   8 minutes ago        Up 13 seconds       0.0.0.0:3000->3000/tcp                                     reaction_reaction_1
aa37198be60c        mongo:3.6.3                       "docker-entrypoint.s…"   20 minutes ago       Up 16 seconds       0.0.0.0:27017->27017/tcp                                   reaction_mongo_1
85c231a58822        oryd/hydra:v1.0.0-beta.9-alpine   "hydra serve all --d…"   31 minutes ago       Up 20 seconds       0.0.0.0:4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp   reaction-hydra_hydra_1
768f5caa0227        postgres:10.3                     "docker-entrypoint.s…"   31 minutes ago       Up 27 seconds       0.0.0.0:32769->5432/tcp                                    reaction-hydra_postgres_1

~$ wget localhost:4000
--2019-01-29 13:50:35--  http://localhost:4000/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:4000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:4000... failed: Connection refused.

**Desktop**
 - OS: Ubuntu Server 18.04.1 LTS

**Comment by rlamostre0** [comment]
`~/reaction-platform$ make start`
`reaction-hydra_postgres_1 is up-to-date`
`Starting reaction-hydra_hydra-migrate_1 ... done`
`reaction-hydra_hydra_1 is up-to-date`
`reaction_mongo_1 is up-to-date`
`reaction_reaction_1 is up-to-date`
`Starting reaction-next-starterkit_web_1 ... done`

`~/reaction-platform$ wget localhost:4000`
`--2019-01-29 14:27:51--  http://localhost:4000/`
`Resolving localhost (localhost)... ::1, 127.0.0.1`
`Connecting to localhost (localhost)|::1|:4000... connected.`
`HTTP request sent, awaiting response... No data received.`
`Retrying.`

`--2019-01-29 14:27:52--  (try: 2)  http://localhost:4000/`
`Connecting to localhost (localhost)|::1|:4000... connected.`
`HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.`
`Retrying.`

`--2019-01-29 14:27:54--  (try: 3)  http://localhost:4000/`
`Connecting to localhost (localhost)|::1|:4000... failed: Connection refused.`
`Connecting to localhost (localhost)|127.0.0.1|:4000... failed: Connection refused.`
`Resolving localhost (localhost)... ::1, 127.0.0.1`
`Connecting to localhost (localhost)|::1|:4000... failed: Connection refused.`
`Connecting to localhost (localhost)|127.0.0.1|:4000... failed: Connection refused.`

`~/reaction-platform$ docker ps`
`CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                      NAMES`
`668ffb16bfdc        reaction-next-starterkit_web      "/usr/local/src/reac…"   3 minutes ago       Up 25 seconds       0.0.0.0:4000->4000/tcp                                     reaction-next-starterkit_web_1`
`c347da831301        reaction_reaction                 "bash -c 'meteor npm…"   11 minutes ago      Up 11 minutes       0.0.0.0:3000->3000/tcp                                     reaction_reaction_1`
`cbd5ca3d4c4b        mongo:3.6.3                       "docker-entrypoint.s…"   12 minutes ago      Up 11 minutes       0.0.0.0:27017->27017/tcp                                   reaction_mongo_1`
`c9075a767da2        oryd/hydra:v1.0.0-beta.9-alpine   "hydra serve all --d…"   20 minutes ago      Up 19 minutes       0.0.0.0:4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp   reaction-hydra_hydra_1`
`dd04303b254c        postgres:10.3                     "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       0.0.0.0:32771->5432/tcp                                    reaction-hydra_postgres_1`

**Comment by rlamostre0** [comment]
This solved my issue

https://github.com/reactioncommerce/reaction-next-starterkit/issues/467#issuecomment-454888237

**Comment by ghost** [comment]
@janus-reith this can be closed

**Comment by janus-reith** [comment]
Agreed, closing this.
