### ISSUE TITLE
Documentation on .env variables

### ISSUE THREAD

**Issue by adrienshen** [reactioncommerce/example-storefront#501]
# Feature Name

### Summary description
Documentation of the .env variables

```
INTERNAL_GRAPHQL_URL=http://reaction.api.reaction.localhost:3000/graphql-alpha
EXTERNAL_GRAPHQL_URL=http://localhost:3000/graphql-alpha
FAVICON_URL=https://assets.reactioncommerce.com/favicon
PLACEHOLDER_IMAGE_URL_GALLERY=/resources/placeholder.gif
PLACEHOLDER_IMAGE_URL_GRID=/resources/placeholder.gif
SEGMENT_ANALYTICS_SKIP_MINIMIZE=true
SEGMENT_ANALYTICS_WRITE_KEY=ENTER_KEY_HERE
KEYCLOAK_REALM=default
KEYCLOAK_CLIENT_ID=reaction-next-starterkit
KEYCLOAK_URL=http://localhost:8080/auth
KEYCLOAK_REDIRECT_URI=http://localhost:4000/auth
STRIPE_PUBLIC_API_KEY=ENTER_STRIPE_PUBLIC_KEY_HERE
OAUTH2_AUTH_URL=http://localhost:4444/oauth2/auth
OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
OAUTH2_CLIENT_ID=reaction-next-starterkit
OAUTH2_CLIENT_SECRET=CHANGEME
OAUTH2_REDIRECT_URL=http://localhost:4000/callback
PASSPORT_SESSION_SECRET=CHANGEME
CANONICAL_URL=http://example.com
```

### Rationale for why this feature is necessary

It's not clear what the variables mean or how users can configure it to their use cases. For example: `INTERNAL_GRAPHQL_URL`, `EXTERNAL_GRAPHQL_URL`, what do these mean and which one would I set to my staging GraphQL url hosted on Digital Ocean?

### Expected use cases

I would like to run the started kit locally, but sometimes connected to externally hosted staging Reaction GraphQL server on Digital Ocean.

**Comment by machikoyasuda** [comment]
Hi @adrienshen @bradlead @yannterzi @arimus - I've added instructions on how to run the Starter Kit locally connected to an externally hosted Reaction GraphQL server in the README: https://github.com/reactioncommerce/reaction-next-starterkit#run-in-development-against-a-production-api

In summary, you'd set the `.env` var for `INTERNAL_GRAPHQL_API` to the production server's graphql-alpha URL, and then run this:`docker-compose run --rm --service-ports web yarn start`. Don't forget the `--service-ports`.

**Comment by aldeed** [comment]
All ENV documented for 3.0.0 release in https://github.com/reactioncommerce/reaction-docs/pull/890
