### ISSUE TITLE
Long order statuses might overflow badge UI

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/example-storefront#515]
Type: **minor**

**Describe the bug**
If a long order status is provided to an OrderCard, the Badge text might overflow and overlap other text. @reactioncommerce/design thoughts on a solution? Wrap the text? Cut it off?

**Screenshots**
![image](https://user-images.githubusercontent.com/4482263/53922175-15caea00-4028-11e9-9550-10985ac8db26.png)

**Comment by zenweasel** [comment]
That looks like a missing translation issue?

**Comment by kieckhafer** [comment]
@zenweasel In this particular case, yes it is a missing translation. However, since we don't limit the length of the possible order statuses, if a translated order status is over 25 characters long, this issue will occur.

**Comment by janus-reith** [comment]
Now that you brought up that topic, Is there any plan on how to hande translations in the nextjs frontend?
Would an implementation be completely decoupled, or use the strings that are in the DB for the meteor API?

Like in this specific case, the backend which serves the status could also provide matching translations. But I'm unsure what a general approach would look like here, or if there would be a noticeable negative impact on performance.

**Comment by janus-reith** [comment]
@zenweasel Will there be translated keys in the starterkit?
