### ISSUE TITLE
Redirect graphql playground (graphiql) to core

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/example-storefront#549]
# Feature Name

### Summary description

I often can't remember where we host our graphql playground (graphiql). Since it's a web app type thing, I often guess it is served by the storefront. In fact it's served by the graphql API server. I'd like to suggest a series of developer-friendliness 30X redirect routes in storefront to make this "just work" even if I forget:

- `/graphql-beta` (actual path used by core)
- `/graphiql` (actual name of the 3rd party project)
- `/graphql` (intuitive guess)
- `/graphql-alpha` (path used until v2.0.0-rc.12)

These should all redirect to: `http://reaction.api.localhost:3000/graphql-beta`, which comes from the `EXTERNAL_GRAPHQL_URL` env var.

### Rationale for why this feature is necessary

Improves developer experience by eliminating potentially frustrating dead ends and error pages.

**Comment by machikoyasuda** [comment]
Following this ticket, this documentation should be updated:

## Documentation updates
- https://docs.reactioncommerce.com/docs/graphql-using#graphql-clients
- https://docs.reactioncommerce.com/docs/installation-reaction-platform
- https://docs.reactioncommerce.com/docs/graphql-intro
- README for `example-storefront`

**Comment by focusaurus** [comment]
@machikoyasuda I don't think we want these new redirects to be the primary, documented way to access graphiql. I think it makes sense to be able to start just reaction core and be doing non-UI development and use the tool from the core server, and I think since that's the simplest and most direct stack and access method, I think that should still remain the official documented way. **However**, if folks, as I often do, stumble at it through the storefront, I think it's nice ergonomics to do this redirect. What do you think?

**Comment by machikoyasuda** [comment]
@focusaurus True! Maybe we can add it to just the Storefront README and forgo the Docs part. (In case it somehow confuses people).
