### ISSUE TITLE
Registered addresses not displayed at Storefront checkout

### ISSUE THREAD

**Issue by mpaktiti** [reactioncommerce/example-storefront#554]
## Issue Description
I have a Storefront user with a saved address at their Address Book, but every time I place an order, I don't get any option to re-use that address, I'm asked to add my address info again.

## Steps to Reproduce
1. Sign up as a new Storefront user
2. Go to Profile > Address Book and add a new address
3. Add a product to your cart and checkout 
4. You are asked to enter a Shipping Address, even though you already have one saved in your Address Book

## Possible Solution
None

### Versions
`"version": "2.0.0"`

**Comment by janus-reith** [comment]
How would you go about this - I don't really get how `AddressCapture` is supposed to be used apart from the basic way it is currently, as I don't see where data for the suggestion view it offers should come from.

I believe implementing `AddressChoice` here is the bigger priority, if there is relevant suggestion data later on, that suggestion part could still be added to the address form in there I guess.

`AddressChoice` is currently used for the payment step, so if we do relevant changes in there we should keep it compatible.

Also, the payment step doesn't seem to care about persisting the data. For the billing step we might want to actually persists the entered address somehow. For users we could add it to their profile as soon as the step is completed, for guest users we only have the current cart address - But in that case we probably don't need to take care of selecting & persisting an address at all.

**Comment by HarisSpahija** [comment]
Hey this issue showed up with our current project and I was wondering if this is still a feature that needs to be supported, or if I can make a PR to remove AddressBook completely? It is at this point just clutter/confusing to keep it there unless we finish the implementation.

**Comment by aldeed** [comment]
@HarisSpahija I don't think there's much left to finish the implementation and it's a useful / expected feature. @kieckhafer might have some memory of where we left off and what the plan was.

**Comment by HarisSpahija** [comment]
@aldeed Weird, I'd assume having AddressBook allows us to set a predefined address somewhere in the checkout. But we haven't actually managed to see where the AddressBook component was being used apart from profile. Is it supposed to show up somewhere? If so, then it must be a bug on our implementation.

**Comment by aldeed** [comment]
@HarisSpahija AddressChoice is here: https://designsystem.reactioncommerce.com/#/Storefront%20Components/Forms/AddressChoice

The places in checkout flow that collect an address were supposed to use AddressChoice, with the account addresses passed in. I don't have time to dig into all the layers right now, but possibly that was the part we never completed? Either checkout is using AddressForm directly instead of AddressChoice, or we are not requesting and passing in the `addresses` so it always renders an AddressForm?

**Comment by kieckhafer** [comment]
I don't recall how far we were - if we had even started - with implementing it, but do know we wanted to do so. @HarisSpahija if adding it is in your plans, please do so, we'd love to have your PR into the codebase.
