### ISSUE TITLE
Cannot view checkout page with 0.00€ total amount

### ISSUE THREAD

**Issue by karaarda** [reactioncommerce/example-storefront#556]
Type: **minor**

**Describe the bug**
When there are only items with 0.00€ price in the cart, the checkout page cannot be viewed.

`web_1  | TypeError: component.renderComplete is not a function                                
web_1  |     at CheckoutActions._this.renderCompleteAction (/usr/local/src/reaction-app/node_modules/@reactioncommerce/components/CheckoutActions/v1/CheckoutActions.js:159:28)
web_1  |     at CheckoutActions._this.renderAction (/usr/local/src/reaction-app/node_modules/@reactioncommerce/components/CheckoutActions/v1/CheckoutActions.js:248:36)
web_1  |     at /usr/local/src/reaction-app/node_modules/@reactioncommerce/components/CheckoutActions/v1/CheckoutActions.js:299:23
web_1  |     at Array.map (<anonymous>)                                                       
web_1  |     at CheckoutActions.render (/usr/local/src/reaction-app/node_modules/@reactioncommerce/components/CheckoutActions/v1/CheckoutActions.js:298:18)
web_1  |     at processChild (/usr/local/src/reaction-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2863:18)
web_1  |     at resolve (/usr/local/src/reaction-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2716:5)
web_1  |     at ReactDOMServerRenderer.render (/usr/local/src/reaction-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3100:22)
web_1  |     at ReactDOMServerRenderer.read (/usr/local/src/reaction-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
web_1  |     at renderToStaticMarkup (/usr/local/src/reaction-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3541:27)
web_1  |     at process (/usr/local/src/reaction-app/node_modules/react-apollo/react-apollo.umd.js:118:24)
web_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)`

**To Reproduce**
1. Create a variant of your favorite product with 0 as the price
2. Go to the storefront
3. Add this free item to your cart
4. Try to view the cart with only this free variant
5. The page won't render

**Expected behavior**
Checkout page being rendered

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox
 - Version 68

**Comment by jitenagarwal19** [comment]
@karaarda were you able to find a fix or workaround for this issue?
