### ISSUE TITLE
Async Stripe is not implemented properly

### ISSUE THREAD

**Issue by jmaver-plume** [reactioncommerce/example-storefront#563]
Type: **critical**

**Describe the bug**
Stripe is added from window to state only on [componentDidMount](https://github.com/reactioncommerce/example-storefront/blob/develop/src/pages/_app.js#L70)

As described in [react-stripe-elements docs](https://github.com/stripe/react-stripe-elements#loading-stripejs-asynchronously) we need to also include an `eventListener` such as example:

```
if (window.Stripe) {
  this.setState({stripe: window.Stripe('pk_test_12345')});
} else {
  document.querySelector('#stripe-js').addEventListener('load', () => 
  // Create Stripe instance once Stripe.js loads
  this.setState({stripe: window.Stripe('pk_test_12345')});
 });
}
```

**To Reproduce**
This error never occured locally for me, only when deployed to server so it is somewhat difficult to reproduce.
1. Deploy storefront
2. Reach the step in checkout process where you have to enter card information.
3. See error, there will be no input fields because stripe has not loaded by the time `componentDidMount` in `_app.js` was called.

**Expected behavior**
Stripe inputs should be visible.

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubunut Mate, macOs Mojave
 - Browser Chrome, Safari, Firefox, Edge
 - Version all newest

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 9
 - Browser Google Chrome

**Additional context**
I have marked this bug as critical, because if people use example-storefront as base for frontend then the only real payment option included is not working properly.

**Comment by albertstartup** [comment]
This solves the problem, thanks!
