### ISSUE TITLE
When inventory tracking is enabled and backorders disabled prevent adding more quantity than is available in inventory to cart.

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/example-storefront#566]
Steps to reproduce:

1. Enable inventory tracking
1. Disable backorders for a product
1. Set quantity in stock to be 1
1. Add two to cart
1. Observe that you can

**Comment by HarisSpahijaPon** [comment]
can we as a community help with this or is this still a thing? We face the same issue currently and have no idea how to solve it.
