### ISSUE TITLE
Remove id param from logout endpoint

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/example-storefront#574]
### Rationale for why this is necessary
The logout endpoint takes the userId in the url param. Meaning that you can pass any known ID to log out a user. Even though we have the id in an encoded form, we should remove the id param.

### Work:
Use `/logout` without the id param. Find alternative to retrieve the current user and the issue to logout api call.

**Comment by janus-reith** [comment]
The nextjs express server should be able to retrieve necessary information from the current session.
It could pass an auth token as header to the backend. The backend should be able to use hydra introspection to retrieve the belonging Reacton user in the same manner other graphql calls are validated and then process the meteor logout.

**Comment by willopez** [comment]
resolved via #637
