### ISSUE TITLE
CI Integration tests failing due to AWS S3 permissions issue

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/example-storefront#581]
I merged a new change into develop and circleci is failing at the integration tests. I investigated and the script that deploys to ECS via propel is failing with this message:

```
Running aws s3 cp s3://reaction-staging-propel-artifacts/propel-linux-amd64 ./propel
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

@spencern Do you have an AWS admin account where we can troubleshoot this. Maybe these credentials got rolled?

It looks like the circleci job does **not** need an explicit context, just environment variables configured on the storefront project itself.

**Comment by spencern** [comment]
Unfortunately I do not have an AWS admin account - I'll see if @griggheo can set me up there when he gets back.

**Comment by focusaurus** [comment]
OK for context it seems like these may have been failing since as early as January based on [this code comment Jeff made in January](https://github.com/reactioncommerce/example-storefront/blob/dc8a5e5563b480835ffddc42391f40918a9f01e9/tests/integration/ssr.test.js#L12).

I think between Grig and I we'll decide if we want to try to fix these or just properly disable/remove them.

If we fix, there's at least an AWS S3 error we can fix probably just by setting the proper env vars and/or circleci context and then seeing if the propel ECS deploy keeps going to completion. But since it may have been long-neglected I suspect there may be a series of issues we need to fix to make it work.

**Comment by spencern** [comment]
Thanks for the plan and for initiative to take this on. 👍
