### ISSUE TITLE
Example storefront failed to build

### ISSUE THREAD

**Issue by moeghashim** [reactioncommerce/example-storefront#586]
Type: **breaking|critical|major|minor**

**Describe the bug**
The store front build fails. It showing that it can't find a module module cookie-parser
I attached a screenshot.

**To Reproduce**
Run `make`

**Expected behavior**
To build the storefront successfully.

**Screenshots**
<img width="817" alt="Screenshot 2019-09-20 12 12 36" src="https://user-images.githubusercontent.com/23550100/65330194-f9506280-dbb1-11e9-8797-22c4c3d82df0.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by focusaurus** [comment]
Can you try git pull the latest develop and see if it starts? There was a commit where we weren't running `yarn install` on start, but it has already been fixed.

**Comment by moeghashim** [comment]
I did a new fresh installation. Stopped containers and deleted images. It's still not solved.

**Comment by moeghashim** [comment]
I compared the current version to the previous one and it seems there is a volume missing. The `example_storefront_empty_node_modules` is missing. Upon checking docker-compose.yml there is a line missing from the previous version. Which is `empty_node_modules:/usr/local/src/reaction-app/node_modules` under `volumes`.

**Comment by moeghashim** [comment]
Thanks to @janus-reith
This solved it for me: Editing the file .reaction/entrypoint.sh in the storefront and change command=(node .) to command=(./bin/start) in Line 21.

**Comment by focusaurus** [comment]
Your manual edit was also merged into [develop here](https://github.com/reactioncommerce/example-storefront/commit/e2df50744143cc26994733b2973eb15539df9836) so if you pull the latest code from github you shouldn't need to have any local modifications. Also FYI the `example_storefront_empty_node_modules` is gone on purpose. Thanks @janus-reith for your help!
