### ISSUE TITLE
[2.8.0] - Oauth client does not initialise

### ISSUE THREAD

**Issue by garyrvaz** [reactioncommerce/example-storefront#606]
Type: **breaking|critical**

**Describe the bug**
```
The OAuth2 request resulted in an error.
Error: invalid_client
Description: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)
Hint: The requested OAuth 2.0 Client does not exist.
Debug:
You are seeing this default error page because the administrator has not set a dedicated error URL (environment variable OAUTH2_ERROR_URL is not set). If you are an administrator, please read the guide to understand what you need to do. If you are a user, please contact the administrator.
```
It is related to https://github.com/reactioncommerce/reaction-platform/issues/41
Might have been caused by changes in #602 
I ran `make` with example-storefront, reaction and reaction-hydra at v2.7.0, the auth pages load fine, but when these at v2.8.0 Oauth client doesn't initialize. Then I tried reaction and reaction-hydra at v2.7.0 and example-storefront at v2.8.0, the was reproduced. After that, I ran reaction and reaction-platform at v2.8.0 and example-storefront at v2.7.0, auth client works.

**To Reproduce**
1. Click on `Sign In` or `Create Account`

**Expected behavior**
Auth page should load for Sign In/Sign up.

**Comment by gslandtreter** [comment]
Seems to be introduced by #603 
./bin/start is no longer called, consequently ./bin/create-hydra-client.js is not executed.
Manually calling ./bin/create-hydra-client.js from the container works around the issue.

**Comment by agustif** [comment]
How can one manually call it ./bin/start, sh /bin/start doesnt work for me.

I can't login on v2.9.0 all packages due to this same problem it seems, as my hydra-client never starts?

**Comment by huangyanxiong01** [comment]
me too

**Comment by ArcadaLabs-Jason** [comment]
Still getting this in 2.9

**Comment by ghost** [comment]
No reports of this happening after v3. Can this be closed? There's new Auth work going into storefront with https://github.com/reactioncommerce/example-storefront/pull/760 and closing out old auth issues seems prudent.
