### ISSUE TITLE
[bug] Login doesnt work in storefront: Message: Cannot return null for non-nullable field Account.primaryEmailAddress.

### ISSUE THREAD

**Issue by agustif** [reactioncommerce/example-storefront#615]
Type: **breaking**

**Describe the bug**
I get the following error in the example-storefront after register/login.
`web_1  | [GraphQL error]: Message: Cannot return null for non-nullable field Account.primaryEmailAddress., Location: [{"line":31,"column":5}], Path: ["viewer","primaryEmailAddress"]`

It seems because of something about defaultEmail, I always keep seing the siggnin/register even if I'm already logged in?

I also cannot checkout properly etc

**To Reproduce**
1. Go to https://storefront.cruceritis.com
2. Click on register/login
3. Open devTools

**Expected behavior**
I would expected to be redirected to a storefront with the user logged in and no signin/register buttons
**Screenshots**
<img width="1680" alt="Screenshot 2019-11-22 at 19 28 02" src="https://user-images.githubusercontent.com/6601142/69450798-42fa2c80-0d5e-11ea-8840-e7abcc3871b2.png">

**Additional context**
I'm deploying to DO with proxy-traefik.

**Comment by aldeed** [comment]
What version was this on? It sounds like something that was fixed in 2.9.1

**Comment by agustif** [comment]
Yep, can close I guess
