### ISSUE TITLE
Create a robots.txt file

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/example-storefront#629]
## Issue Description
We need to create a robots.txt file to the root. The file should allow all bots to crawl the site and index it.  With the exception of the "resources" folder for which there is no need to be indexed.

**Comment by HarisSpahijaPon** [comment]
I disagree we should add this, this is part of deployment and belongs in the DevOps part of development. Example storefront should not default to indexing, that seems to me up to the developers that are using example storefront.
