### ISSUE TITLE
Checkout error in MS Edge: Unable to get property 'props' of undefined or null reference

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/example-storefront#630]
## Issue Description
When trying to checkout with MS Edge, nothig happens when you click save on the adress form.
This happens both in the profile page and during checkout.
Console throws: 

> Unable to get property 'props' of undefined or null reference

Following the linked code in that error leads to this:

```
    _defineProperty(this, "onAdd", function (address) {
      let validateAddress = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;
      const {
        addAddress,
        onError,
        updateAddress
      } = _this.props; // if edit address is in the address book form
```

Didn't investigate further yet.

## Steps to Reproduce
1. Add item to cart
2. Go to checkout
3. Enter Adress data
4. Press save and observe how the adress is not saved and the checkout workflow doesn't continue.
5. open console, find the error stated above.

## Possible Solution
Missing polyfill, misconfigured transpilation?

### Versions
v2.0.0-rc.7 and older, 1.x branch aswell.

**Comment by aldeed** [comment]
Transferred from the API repo. We should just verify this isn't an issue on the example storefront and then close.

**Comment by HarisSpahijaPon** [comment]
@aldeed how can we verify this? So far I could not reproduce this issue on MS Edge.

**Comment by aldeed** [comment]
@HarisSpahijaPon That's good enough for me to close this. I am pretty sure this was referring to the old checkout page. Anyone coming here seeing new Edge issues can submit a new issue in this repo.
