### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by loid345** [reactioncommerce/example-storefront#641]
Hello. When do you plan to add PWA support (Progressive Web App)?

**Comment by aldeed** [comment]
@volanar Are there specific PWA features you're looking for?

**Comment by loid345** [comment]
> @volanar Are there specific PWA features you're looking for?

https://nextjs.org/features/progressive-web-apps

**Comment by HarisSpahijaPon** [comment]
I think with the current usage of apolloclient we could get pretty far. Maybe something that can be worked on in the v3 cycle? I'd love to help on this one

**Comment by aldeed** [comment]
@volanar I'm trying to understand which specific features? The example storefront is already what I would call "PWA-compatible". It supports either server or client routing. You can easily enable the NextJS offline support I assume.

I'm going to guess what might be the deficiencies:
- Make it easier / document how to do offline data with Apollo Client
- If you're thinking about mobile, then maybe a few UI bugs on small screens
- If for mobile, then maybe some optimization to make sure we aren't loading extra data and we're taking advantage of caching as much as possible.

This is a good idea, but it needs to be broken down into much smaller pieces of what specifically is missing for PWA use case.
