### ISSUE TITLE
[ESv2] Refactor all components to match component context

### ISSUE THREAD

**Issue by HarisSpahijaPon** [reactioncommerce/example-storefront#643]
# Refactor all components to match component context

### Summary description
I noticed that when implementing i18next a lot of components do not have a reference in component context. For example CheckoutActions and CheckoutTopHat are not defined in the component context. 

### Rationale for why this feature is necessary
All items that can/should be inherited from the component context should be moved to there. It makes an easier development experience and a better overview of all the components. 
Also the documentation about creating custom components and using component context should be updated prior to 3.0 release. 

### Expected use cases
Custom component implementation, overriding or passing props to components.

**Comment by aldeed** [comment]
Agree with this. May not get into 3.0 release but soon after.
