### ISSUE TITLE
Add an ability to repeat a previous order («Reorder»)

### ISSUE THREAD

**Issue by dmitry-fedyuk** [reactioncommerce/example-storefront#671]
### Expected behavior
It would be nice to provide an ability to customers to repeat their previous orders with a «**Reoder**» button:
![01](https://user-images.githubusercontent.com/83204/35188373-5c3bd2f4-fe5e-11e7-9561-d445bc878e45.png)

An example from Magento 2:
![02](https://user-images.githubusercontent.com/83204/35188375-6626bd60-fe5e-11e7-8367-cb3d6b35fde8.png)
![03](https://user-images.githubusercontent.com/83204/35188376-6b565214-fe5e-11e7-97a7-16de65a694db.png)

### Actual behavior
There is no such ability...

### Steps to reproduce the behavior
Place an order and go to your own account (profile).

### Versions
> Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master

**Comment by aldeed** [comment]
Moved this to example-storefront since it should be possible to implement this entirely in the storefront without API changes.

**Comment by janus-reith** [comment]
Would such a reorder feature just take care of adding the same items to you cart again and maybe set the shipping address, or actually take care of placing the whole order?
The former would probably be easy to implement, the latter could get more complex with things like payments, which would also need to be authorized again.

One thing to keep in mind is, that the billing address is not stored on the cart permanently, so it might be the most simple solution if that button just adds items to cart, sets the shipping address and takes you the payment step and pre-fills the billing address client side.

Some more considerations:
- What if the current user already has items in the cart? Only one cart is allowed per account, and if we just add cart items to that existing cart, it might under some circumstances influence which shipping rates are available, and which payment types.
- Also with just the same items that should be added to cart, availability might change or some shipping or payment option could not be available anymore. There should be fallbacks for each of these steps.

**Comment by aldeed** [comment]
@janus-reith All good questions. It seems the first two simple implementations of this would be an `Add to Cart` button next to each item when viewing previous orders, and an `Add All to Cart` button for the order itself.

For more of a one-click reorder, it might be possible to skip the cart entirely. You can call `placeOrder` without there ever having been a cart. But we haven't really tested this approach in a UI, there could be bugs or unintentional dependencies on cart during checkout that we'd need to fix. Plus you would have to write a slightly different checkout page that builds OrderInput without saving anything to cart.
