### ISSUE TITLE
Find out what causes error-fetching-graphql Error: Tag not found

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/example-storefront#679]
Type: minor

**Describe the bug**
Find out what causes `error-fetching-graphql Error: Tag not found`. This occurs during the fetch for static data called in `getStaticProps`. We could consider adding a log to console for each of the functions I created in `staticUtils`, to better determine what slug/_id/name was used in a call, also later durng runtime if a page is revalidated or created during fallback. See https://github.com/reactioncommerce/example-storefront/pull/667#issuecomment-616207068 for more context.

**Comment by rondlite** [comment]
it seems the slug '-' is used which is an impossible slug (as in can't register it). I get this under the variable used to query graphql as slugOrId

**Comment by rondlite** [comment]
I am seeing `Components` from `react` being imported in files under the `[lang]` folder meaning there is component in `/pages` and any component under that folder is seen as a page according to nextjs docs.
