### ISSUE TITLE
Begin TypeScript Migration?

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#709]
# Summary description

Migrate project to TypeScript.

## Implementation

Looks like an easy win as TS can be adopted incrementally. To add support in this project simply:

```sh
yarn add --dev typescript && touch tsconfig.json && dc down && dc up -d
```

Next.js will populate the `tsconfig.json` file with some sane defaults as the container comes up and you can start renaming source files to end with `ts` and `tsx`. (Note at least one TypeScript file is required in the project before the `tsconfig.json` file will be autopopulated with defaults.)

Step two would be to get rid of the `prop-types` dependency. If all goes well, start porting other parts of the framework. Consider pairing this work with https://github.com/reactioncommerce/example-storefront/issues/643.

## Motivation

Type safety. IntelliSense. Better static code analysis resuling in fewer regressions.

## Notes

Doesn't seem to work on the v3.1.0 tag but worked for me on trunk. Probably a Next.js update which allows the `tsconfig.json` file to auto-generate.

**Comment by janus-reith** [comment]
Incremental Migration to Typescript indeed is really simple with nextjs.
However, I think this is a general decision that needs to be made across the stack.
On the api, migration to typescript could come with other benefits and help generalizing schemas.
