### ISSUE TITLE
Shop name not persisting on Mobile Nav

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#710]
Type: **minor**

**Describe the bug**
Shop name is not persisting on the mobile navigation.

**To Reproduce**
1. Set shop name via admin app.
2. Observe shop name displays in Header.
3. Shrink viewport size to display mobile navigation.
4. Open mobile navigation and observe shop name

**Expected behavior**
Shop name appears consistently across the app.

**Screenshots**

![Peek 2020-07-28 16-01](https://user-images.githubusercontent.com/65664227/88636494-98f05280-d0eb-11ea-8239-f76bf8dd172a.gif)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Ungoogled Chromium
 - Version: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)

**Additional context**
Observed on `release-next-v3.2.0` branch. `shop` prop is `undefined` in `NavigationMobile`.

**Comment by janus-reith** [comment]
@balibebas Could you check it the same error is present on the trunk branch aswell?
It is more up to date than `release-next-v3.2.0` currently.

**Comment by ghost** [comment]
@janus-reith I meant to update this after checking before. Yes, same issue on `trunk`.

**Comment by ihalton** [comment]
@janus-reith @balibebas hello, I met the issue too, and I submit a PR to fix it. Who is our Community PR reviewer? 
It is helpful when the pr can be reviewed. Thanks
