### ISSUE TITLE
Segment Analytics sending empty payloads

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#711]
Type: **minor**

**Describe the bug**
Segment is sending empty payloads in development on `trunk`. It's only sending Page events. It doens't capture any page other than `/` and it's no longer sending other tracking events.

**To Reproduce**
1. Rebuild and start app in development using `trunk` branch.
2. Add `SEGMENT_ANALYTICS_WRITE_KEY` in `.env`
3. Load a page
4. See highlighted item in screenshot (the working events are using the v3.1.0 image)

**Expected behavior**
Segment receives data in its payloads. It also sends other tracking events.

**Screenshots**

![Screen Capture_select-area_20200728192107](https://user-images.githubusercontent.com/65664227/88659889-5db04c80-d108-11ea-8ca0-fe563831c1de.png)

Note the bottom portion is running `3.1.0` and the top is running trunk.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Ungoogled Chromium
 - Version: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)

**Additional context**
n/a

**Comment by janus-reith** [comment]
@balibebas I don't see what's wrong here, could you elaborate further on the issue? What I see highlighted here is a Page view for "/", I wouldn't expect any further payload data to be attached to that.

**Comment by ghost** [comment]
@janus-reith I added some more details to the OP. Essentially no events are being sent for typical tracking purposes and only page events are coming through and the payload is always empty or mostly empty. This is a regression. The best way to see it is to wire up a test Segment account or observe the payloads being sent with a client-side proxy or devtools.

**Comment by janus-reith** [comment]
@balibebas I think this is covered by https://github.com/reactioncommerce/example-storefront/issues/676

**Comment by janus-reith** [comment]
@balibebas I think this is covered by https://github.com/reactioncommerce/example-storefront/issues/676.
Closing this, but happy to reopen if you disagree.
