### ISSUE TITLE
Back button must be pressed twice to leave PDP

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#713]
Type: **minor**

**Describe the bug**
When navigating to a product the URL updates twice and requires two back-button presses to leave. The interim page has an incorrect title.

**To Reproduce**
1. Start 3.1.0 production build
2. Click on a product from homepage
3. Press the back button
4. Press the back button again

**Expected behavior**
Only one back-button press is required to navigate back to the homepage after viewing product details.

**Screenshots**
![Peek 2020-07-28 20-53](https://user-images.githubusercontent.com/65664227/88668408-2a27ef00-d115-11ea-8bae-7d6003dadd3d.gif)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Ungoogled Chromium
 - Version: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)

**Additional context**
Not a `3.2.0` regression but an existing issue.

**Comment by janus-reith** [comment]
The back button routing itself probably works fine, but what happens is that first we route to the product page, and next set the url to point directly to that variant: https://github.com/reactioncommerce/example-storefront/blob/f8dbd9e6a4800b3b3d87d193bfae88f989b35b90/components/ProductDetail/ProductDetail.js#L77

In v3.1 we used `Router.pushRoute `with `{ replace: true }`, from next-routes, now we use the builtin `Router.replace` and not `Router.push`.

I would have expected both implementations to not create another entry in the session history, as described here:
https://nextjs.org/docs/api-reference/next/router#routerreplace

I wonder what's wrong here and if this is a nextjs bug.

**Comment by Eduard-Hasa** [comment]
I noticed this issue as well on mobile specifically on the latest reaction commerce 3.8. If you are on product page and swipe to go page to previous page it just shows same product page again until you do it again finally actually taking you back to previous page.
