### ISSUE TITLE
Upgrade to nextjs 9.5.1

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/example-storefront#715]
# Feature Name
We should upgrade to nextjs v9.5.1.

### Summary description
Upgrade next to v9.5.1, shift the rewrites and redirects in `nextjs.config.js` up and and out of the experimental key, remove `unstabe_` prefix from `getStaticProps` `revalidate`.

### Rationale for why this feature is necessary
Since v9.5.0, the remaining experimental features we make use of ( `unstable_revalidate`, `redirects`+`rewrites` under `experimental` key in `nextjs.config.js`) are now marked as stable: https://github.com/vercel/next.js/releases/tag/v9.5.0

**Comment by ghost** [comment]
Consider superseding by #755. The Next 10 upgrade refactoring was very straightforward. Next 11 right around the corner.
