### ISSUE TITLE
Double-click required to show orders in profile

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#719]
Type: **minor**

**Describe the bug**
In the user account dialog users must double-click _Orders_ to view their orders.

**To Reproduce**
1. Go to a user profile after login.
2. Click on Orders (filling an order first if necessary)
3. Observe nothing happens with single-click.
4. Double-click Orders
5. Observe Orders are now displayed, if any.

**Expected behavior**
A single-click is used to switch between account/order tabs in the user profile.

**Screenshots**

![reaction-account-ux-issue](https://user-images.githubusercontent.com/65664227/89117998-ea765400-d4d4-11ea-99e4-4939320f7a7f.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Ungoogled Chromium
 - Version: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)

**Additional context**
If a single-click is not feasible for some reason add helper text to the sceen letting the user know.

**Comment by janus-reith** [comment]
This has been documented previously in the component library: https://github.com/reactioncommerce/reaction-component-library/issues/434

The upcoming version currently in the `trunk` branch does not make use of `InPageMenu` anymore, as I replaced it with a default Material UI `List` component.

**Comment by ghost** [comment]
Good deal. Checking trunk slipped my mind this time around. Thanks for fixing that.
