### ISSUE TITLE
Static logo URL is visible in reaction admin but not in the Storefront

### ISSUE THREAD

**Issue by hamza0200** [reactioncommerce/example-storefront#720]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Have you added primary logo URL?

## Issue Description 
We are trying to add primary logo URL from the [admin shop](http://localhost:4080/settings/shop) the logo is attaching to the reaction admin but not in the storefront. We have tried to stop/start docker and  even tried to reset cache multiple times but it doesnot work at all. There is no error in console.

Please [see here](https://imgur.com/a/FaTa2LY)

## Steps to Reproduce
1. Login to reaction admin dashboard
2. Navigate to Settings > Shop > Shop Logos
3. Add a URL of logo under "Primary logo URL" text field

## Possible Solution
When a logo URL is attached it should be displayed in the storefront.
There is no option to select between text-based shop name or image-logo to display in storefront.

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
I'm going to transfer this issue from `reaction-development-platform` to `example-storefront`. I'll leave this issue open for the time being for further discussion, but I believe it should be closed, hopefully the answer below satisfies your questions.

_____

The Reaction API, Reaction Admin, and Example storefront are three independent applications at this point. The Reaction API is the real workhorse, while the Admin and Example Storefront are provided to be examples of _**some of the things**_  you can do, not necessarily _**everything**_ that can be done. The goal is for you to take it as a base, and expand upon it.

In this particular instance, what you are experiencing is strictly a design decision in the provided Example Storefront, and isn't related to any issues in the API or Admin. Your shop logo URL is still available via the API on the shop side, it just isn't shown.

To show the logo instead, you can update the following code in your fork of Example Storefront: https://github.com/reactioncommerce/example-storefront/blob/trunk/components/Header/Header.js#L71-L75

The shop logo is available on the `shop` object that is already provided:
```
{
  "data": {
    "shop": {
      "shopLogoUrls": {
        "primaryShopLogoUrl": "https://reactioncommerce.com/img/logo@2x.png"
      }
    }
  }
}
```

**Comment by balibebas** [comment]
Erik gave a nice, concise summary above. You can use that info to run an [`updateShop` mutation](https://github.com/reactioncommerce/reaction/blob/98ef20a54ffc3dd2586f75c16ead858e57ab6955/src/core-services/shop/mutations/updateShop.js) to add a `primaryShopLogoUrl` which will then appear for the primary shop in the MongoDB. Here's an example mutation:

```graphql
mutation AddShopLogo {
  updateShop(
    input: {
      shopId: "cmVhY3Rpb24vc2hvcDphU1lHMnhtZkNGRkZrampCZQ==",
      shopLogoUrls: {
        primaryShopLogoUrl: "https://cdn5.telesco.pe/file/hIM4j2NVUqNwSGj37jaa76SFbWrCRQVP01iOzVoAFgLLX2ZAeDiQfwL1x667i_jZU3vjXGorO386FQbWyVhexflnj02vEXEiE8_DCWhKfbsaDcTEPJq-HG0QSa-V43zzSuxCOG5Ghuo2clw4ADEksy4pm7WnXKcv2DVQFEcxuMfjcia7lTZ3htSZSpKzFmSE2t7QJTlwulP32VqxYnCJXxFm5hZirg-53UiZS3obmER94au0ew1qUY6YO8DcKt4Rh0CVuP3QCSvaiWNtOK9ys_z3f7la6PTXgNdAnwro9DNCNktBWZwzphZxdjRUOUMsfBZEGDufGxxuqaux_arE-g.jpg"
      }
    }
  ),
  {
    shop {
      shopLogoUrls {
        primaryShopLogoUrl
      }
    }
  }
}
```

It's worth pointing out that the Example Storefront uses `ShopLogo` from the [reaction-component-library](https://github.com/reactioncommerce/reaction-component-library) to set its logo and [that component expects](https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/components/ShopLogo/v1/ShopLogo.js#L38-L41) the logo to be a graphic or text (but not both). Generally this behavior could be modified using a custom component and updating `componentsContext.js` with your custom component but `ShopLogo` isn't configured to be overridden in the latest `example-store` release.

**Comment by ghost** [comment]
Erik gave a nice, concise summary above. You can use that info to run an [`updateShop` mutation](https://github.com/reactioncommerce/reaction/blob/98ef20a54ffc3dd2586f75c16ead858e57ab6955/src/core-services/shop/mutations/updateShop.js) to add a `primaryShopLogoUrl` which will then appear for the primary shop in the MongoDB. Here's an example mutation:

```graphql
mutation AddShopLogo {
  updateShop(
    input: {
      shopId: "cmVhY3Rpb24vc2hvcDphU1lHMnhtZkNGRkZrampCZQ==",
      shopLogoUrls: {
        primaryShopLogoUrl: "https://cdn5.telesco.pe/file/hIM4j2NVUqNwSGj37jaa76SFbWrCRQVP01iOzVoAFgLLX2ZAeDiQfwL1x667i_jZU3vjXGorO386FQbWyVhexflnj02vEXEiE8_DCWhKfbsaDcTEPJq-HG0QSa-V43zzSuxCOG5Ghuo2clw4ADEksy4pm7WnXKcv2DVQFEcxuMfjcia7lTZ3htSZSpKzFmSE2t7QJTlwulP32VqxYnCJXxFm5hZirg-53UiZS3obmER94au0ew1qUY6YO8DcKt4Rh0CVuP3QCSvaiWNtOK9ys_z3f7la6PTXgNdAnwro9DNCNktBWZwzphZxdjRUOUMsfBZEGDufGxxuqaux_arE-g.jpg"
      }
    }
  ),
  {
    shop {
      shopLogoUrls {
        primaryShopLogoUrl
      }
    }
  }
}
```

It's worth pointing out that the Example Storefront v3.1.0 uses `ShopLogo` from the [reaction-component-library](https://github.com/reactioncommerce/reaction-component-library) to set its logo and [that component expects](https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/components/ShopLogo/v1/ShopLogo.js#L38-L41) the logo to be a graphic or text (but not both). So you'll likely want to customize either way.

Generally customization of something like `ShopLogo` could be adjusted using a _custom_ component and updating `src/custom/componentsContext.js` but `ShopLogo` isn't configured to be overridden in that file currently so you're going to end up adjusting the `Header` component directly for the desired result @hamza0200.

---

To use `primaryShopLogoUrl` add the following to `primaryShop.gql` (no service restart required):

```
shopLogoUrls {
  primaryShopLogoUrl
}
```

Also, don't forget to update the `NavigationMobile`, `Checkout` and `Login` when creating your own `ShopLogo`. You can create your own custom `ShopLogo` by copying the one in the `reaction-component-library` and changing the relative import to:

```
import { addTypographyStyles, applyTheme } from "@reactioncommerce/components/utils";
```

**Comment by mian-muhammad** [comment]
@balibebas shouldn't it be `/staticUtils/shop/primaryShop.js` instead of `primaryShop.gql`, you can add

```javascript
shopLogoUrls {
  primaryShopLogoUrl
}
```

Inside this [code snippet](https://github.com/reactioncommerce/example-storefront/blob/f8dbd9e6a4800b3b3d87d193bfae88f989b35b90/staticUtils/shop/primaryShop.js#L2-L14), which should then look like this

```javascript
query primaryShop($language: String! = "en") {
  primaryShop {
    _id
    shopLogoUrls {
      primaryShopLogoUrl
    }
    currency {
      code
    }
    defaultNavigationTree(language: $language) {
      ...NavigationTreeFragment
    }
    description
    name
  }
}
```
And you should be getting something like this inside your `shop` object:

```javascript
 {
   _id: 'cmVhY3Rpb24vc2hvcDpDTG9hYzlkU3RFUUUzYUgySg==',
   currency: { code: 'USD' },
   shopLogoUrls: { primaryShopLogoUrl: 'https://logodix.com/logo/2063476.png' },
   defaultNavigationTree: {
     _id: 'cmVhY3Rpb24vbmF2aWdhdGlvblRyZWU6YU1kUmZld2JSeW1uejJtUno=',
     shopId: 'cmVhY3Rpb24vc2hvcDpDTG9hYzlkU3RFUUUzYUgySg==',
     name: 'Main Navigation',
     items: [ [Object] ]
   },
   description: null,
   name: 'DevShop'
 }
```

I couldn't find a file named `primaryShop.gql`. Could you please elaborate path for this `primaryShop.gql` file.

**Comment by ghost** [comment]
Thanks @hamza0200. I updated my instructions to specify the storefront version the instructions applied to (`v3.1.0`). I see in `trunk` the file moved and the one you've referenced looks like the correct place for the refactor.

**Comment by mian-muhammad** [comment]
> Erik gave a nice, concise summary above. You can use that info to run an [`updateShop` mutation](https://github.com/reactioncommerce/reaction/blob/98ef20a54ffc3dd2586f75c16ead858e57ab6955/src/core-services/shop/mutations/updateShop.js) to add a `primaryShopLogoUrl` which will then appear for the primary shop in the MongoDB. Here's an example mutation:
> 
> ```graphql
> mutation AddShopLogo {
>   updateShop(
>     input: {
>       shopId: "cmVhY3Rpb24vc2hvcDphU1lHMnhtZkNGRkZrampCZQ==",
>       shopLogoUrls: {
>         primaryShopLogoUrl: "https://cdn5.telesco.pe/file/hIM4j2NVUqNwSGj37jaa76SFbWrCRQVP01iOzVoAFgLLX2ZAeDiQfwL1x667i_jZU3vjXGorO386FQbWyVhexflnj02vEXEiE8_DCWhKfbsaDcTEPJq-HG0QSa-V43zzSuxCOG5Ghuo2clw4ADEksy4pm7WnXKcv2DVQFEcxuMfjcia7lTZ3htSZSpKzFmSE2t7QJTlwulP32VqxYnCJXxFm5hZirg-53UiZS3obmER94au0ew1qUY6YO8DcKt4Rh0CVuP3QCSvaiWNtOK9ys_z3f7la6PTXgNdAnwro9DNCNktBWZwzphZxdjRUOUMsfBZEGDufGxxuqaux_arE-g.jpg"
>       }
>     }
>   ),
>   {
>     shop {
>       shopLogoUrls {
>         primaryShopLogoUrl
>       }
>     }
>   }
> }
> ```
> 
> It's worth pointing out that the Example Storefront v3.1.0 uses `ShopLogo` from the [reaction-component-library](https://github.com/reactioncommerce/reaction-component-library) to set its logo and [that component expects](https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/components/ShopLogo/v1/ShopLogo.js#L38-L41) the logo to be a graphic or text (but not both). So you'll likely want to customize either way.
> 
> Generally customization of something like `ShopLogo` could be adjusted using a _custom_ component and updating `src/custom/componentsContext.js` but `ShopLogo` isn't configured to be overridden in that file currently so you're going to end up adjusting the `Header` component directly for the desired result @hamza0200.
> 
> To use `primaryShopLogoUrl` add the following to `primaryShop.gql` (no service restart required):
> 
> ```
> shopLogoUrls {
>   primaryShopLogoUrl
> }
> ```
> 
> Also, don't forget to update the `NavigationMobile`, `Checkout` and `Login` when creating your own `ShopLogo`. You can create your own custom `ShopLogo` by copying the one in the `reaction-component-library` and changing the relative import to:
> 
> ```
> import { addTypographyStyles, applyTheme } from "@reactioncommerce/components/utils";
> ```

@balibebas would you mind telling me where is this `primaryShop.gql` file is?

**Comment by ghost** [comment]
@mian-muhammad Of course. See [the 3.1.0 tag](https://github.com/reactioncommerce/example-storefront/tags), the version I mentioned. That's the latest stable storefront release.

**Comment by mian-muhammad** [comment]
@balibebas can you elaborate difference between `trunk` and `v3.1.0`

**Comment by ghost** [comment]
> @balibebas can you elaborate difference between `trunk` and `v3.1.0`

@mian-muhammad that's more of an offline conversation probably more appropriate for Gitter.

**Comment by mian-muhammad** [comment]
> > @balibebas can you elaborate difference between `trunk` and `v3.1.0`
> 
> @mian-muhammad that's more of an offline conversation probably more appropriate for Gitter.

Oh great, I was at `trunk`.
