### ISSUE TITLE
Checkout Missing Product Images

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/example-storefront#735]
Type: **minor**

**Describe the bug**
Checkout page not showing product images when images are available.

**To Reproduce**
1. Add an item to the Cart
2. Click on Cart
3. Observe the `CartItem` appear without an image.

**Expected behavior**
Product images appear as expected Checkout.

**Screenshots**
This one image says it all.

<img width="1446" alt="Screen Shot 2020-10-20 at 5 19 08 PM" src="https://user-images.githubusercontent.com/65664227/96567862-e1d63280-12f9-11eb-934b-d893c141ed54.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur — Version 11.0 Beta (20A5395g)
 - Browser: Vivaldi
 - Version: 3.3.2022.47 (Stable channel) (64-bit)

**Additional context**
Products without images appearing in Cart appear correctly on Shopping List and Product Details pages. It's also not clear if the images should appear in the mini-cart and if they should this issue exists there as well.

**Comment by janus-reith** [comment]
This is not a storefront issue, closing it.
I created an issue about this some time ago in the files plugin: https://github.com/reactioncommerce/reaction/issues/6488

**Comment by ghost** [comment]
Glad to have these two issues linked now. Thanks for closing the dupe and pointing the way towards the root cause, Janus.
