### ISSUE TITLE
Stripe instructions not working.

### ISSUE THREAD

**Issue by meiremans** [reactioncommerce/example-storefront#791]
Type: **breaking**

**Describe the bug**
In a new setup we cannot add Stripe according to the instructions mentioned.
Step 2 mentions you have to go to reaction classic running at localhost:3000. but this just returns "Cannot GET /"

**To Reproduce**
1. New installation of opencommerce
2. Go to localhost:3000
3. See error

**Expected behavior**
localhost:3000 to show the login page so we can complete the stripe process
OR
update the documentation.

(whichever is applicable)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser Firefox
 - Version latest
 
[the readme](https://github.com/reactioncommerce/example-storefront/blob/trunk/README.md#configuration)

Also worth noticing that in the admin panel localhost:4080 you can press enable in the payment methods section on "stripe card" but nothing happens.

**Comment by meiremans** [comment]
So I see there is an issue open with Stripe that you are handling, great!

When the Strong Customer Authentication is in place, could you also update the readme so I (and every one after me) can implement it?

Thank you.

**Comment by MohanNarayana** [comment]
Hi @meiremans , the doc needs correction. You should find admin (step 2) at http://localhost:4080 and then proceed with enabling Payments and Shipping.
