### ISSUE TITLE
Payment methods does not available

### ISSUE THREAD

**Issue by OlehObodin** [reactioncommerce/example-storefront#817]
Type: **breaking|critical|major|minor**

**Describe the bug**

**To Reproduce**
Enable Stripe
Enable IOU

**Expected behavior**
I should see the form with  payment credentials

**Error**
When trying to buy got  the error
`
 Variable "$shopId" of non-null type "ID!" must not be null. `

**Comment by thecaffeinatedengineer** [comment]
I'm getting the same issue as well. 

@OlehObodin Did you manage to resolve this issue ?

**Comment by OlehObodin** [comment]
@ianchikwature  I have played with versions. So tag v.4.18 for admin, and v.5.1.3 for storefront  have made it work.

**Comment by thecaffeinatedengineer** [comment]
@OlehObodin Thanks for the reply.

[admin tags](https://github.com/reactioncommerce/reaction-admin/tags) only go up to v4.0.0-beta, did you mean the reaction API,  [v4.1.8](https://github.com/reactioncommerce/reaction/releases/tag/v4.1.8) tag?
